[project]
name = "hf-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "fastapi>=0.119.0",
    "openai>=2.3.0",
    "python-dotenv>=1.1.1",
    "uvicorn[standard]>=0.37.0",
]
